# Uncomment this line to define a global platform for your project
# platform :osx, '10.9'

source 'https://github.com/CocoaPods/Specs.git'

target 'LEDControllerApp' do
	pod 'ORSSerialPort'
	xcodeproj 'LEDControllerApp.xcodeproj'
end

